name: Maven unit test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - story-[0-9]
      - dev

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: maven 
    - name: Run coverage with Maven
      run: mvn clean test
    - name: Publish Surefire Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1